Enable kill-ports to handle port number arguments

diff --git a/bin/kill-port b/bin/kill-port
--- a/bin/kill-port
+++ b/bin/kill-port
@@ -1,9 +1,11 @@
 #!/usr/bin/env bash
 
 #
-# kill-port
+# kill-port [PORTS...]
 #
 # List all processes listening on TCP ports, kill any selected.
+#
+# If ports are passed as arguments, kill any processes listening on those ports.
 #
 # Options:
 #   -h    display this message
@@ -15,31 +17,54 @@ usage() {
     grep '^#' < "$0" | tail -n +2 | cut -c 3-
 }
 
+PORTS=""
+IGNORED=""
+
 while [ $# -gt 0 ]; do
-    case "$1" in
-        -h|--help)
+    arg="${1}"
+    shift || true
+
+    case "${arg}" in
+        -h|--help|help)
             usage
             exit 2
             ;;
-        -*)
-            echo "Unknown argument: $1" 1>&2
-            usage
-            exit 1
+          *)
+            if [[ $arg =~ ^[[:digit:]]+$ ]]; then
+              [[ -n "$PORTS" ]] && arg="|${arg}"
+              PORTS="${PORTS}${arg}"
+            else
+              IGNORED="${IGNORED} ${arg}"
+            fi
             ;;
-    esac
-done
+        esac
+      done
+
+if [[ -n "${PORTS}" ]] || [[ -n "${IGNORED}" ]]; then
+  if [[ -n "${PORTS}" ]]; then
+    for pid in $(lsof -wnP -i tcp | grep -E "${PORTS}" | awk '{ print $2 }'); do
+      kill $pid
+    done
+  fi
+
+  [[ -n "${IGNORED}" ]] && echo "Ignored invalid port numbers: ${IGNORED}"
+
+  exit 0
+fi
 
 listeners="$(lsof -wnP -i tcp)"
-test -z "$listeners" && exit 0
+[[ -z "$listeners" ]] && exit 0
 
-pids="$(echo "$listeners" |\
-        awk '{ printf("%-15s%-10s%-10s%-20s\n", $1, $2, $8, $9) }' |\
-        fzf --exact --multi --reverse --no-sort --border |\
-        awk '{ print $2 }' |\
-        sort --unique |\
-        grep --invert-match PID |\
-        tr '\n' ' ')"
-test -z "$pids" && exit 0
+pids="$(
+  echo "$listeners" |\
+  awk '{ printf("%-15s%-10s%-10s%-20s\n", $1, $2, $8, $9) }' |\
+  fzf --exact --multi --reverse --no-sort --border |\
+  awk '{ print $2 }' |\
+  sort --unique |\
+  grep --invert-match PID |\
+  tr '\n' ' '
+)"
+[[ -z "$pids" ]] && exit 0
 
 echo "kill $pids"
 eval kill "${pids[@]}"
