Add dependency checks to pd install script

diff --git a/lib/install-pd b/lib/install-pd
--- a/lib/install-pd
+++ b/lib/install-pd
@@ -5,6 +5,23 @@
 
 set -ex
 
+source "${ASDF_DIR}/asdf.sh"
+
+if [[ -z "$(command -v go)" ]]; then
+  echo "Warning: go executable not found. Skipping p/d installation."
+  exit 1
+fi
+
+if [[ -z "${XDG_DATA_HOME}" ]]; then
+  echo "Warning: XDG_DATA_HOME env var not set. Skipping p/d installation."
+  exit 1
+fi
+
+if [[ -z "${DOTFILES_DIR}" ]]; then
+  echo "Warning: DOTFILES_DIR env var not set. Skipping p/d installation."
+  exit 1
+fi
+
 builtin cd ${XDG_DATA_HOME}/pd
 
 go get
