KLL: Update configuration

diff --git a/home/bin/ergodox b/home/bin/ergodox
--- a/home/bin/ergodox
+++ b/home/bin/ergodox
@@ -1,12 +1,17 @@
 #!/usr/bin/env bash
 
-[[ -z "$1" ]] && exit 1
+set -e
+
+if [[ -z "$1" ]]; then
+  echo "Usage: ergodox (copy|flash)"
+  exit 1
+fi
 
 DOWNLOAD_DIR="$HOME/Downloads"
 CONFIG_DIR="$HOME/.dotfiles/kll_config"
 
 function flash_ergodox() {
-  [[ -z "$1" ]] && exit 1
+  [[ -z "$1" ]] && echo "missing 'left' or 'right' argument" && exit 1
 
   if [[ ! -z "$(ls "$DOWNLOAD_DIR"/MDErgo1-Default-*.zip 2> /dev/null)" ]]; then
     rm -rf "$CONFIG_DIR"
