Git: Add error checking to git cli / clo

diff --git a/home/bin/git-clock-in b/home/bin/git-clock-in
--- a/home/bin/git-clock-in
+++ b/home/bin/git-clock-in
@@ -22,6 +22,18 @@ if [[ -z "$*" ]]; then
     exit 1
 fi
 
+# Check if already clocked in
+CLOCK_IN="$(git show HEAD | grep CLOCK-IN: | awk '{ print $2 }')"
+
+if [[ -n "${CLOCK_IN}" ]]; then
+    echo "Error: Already clocked in. Did you forget to clock out?"
+    exit 1
+fi
+
 SUBJECT="$*"
 
-git commit --allow-empty --message "${SUBJECT}"
+git commit --allow-empty --message "${SUBJECT}
+
+START: $(date +'%a,%e %b %Y %T %z')
+CLOCK-IN: $(date +%s)
+"
diff --git a/home/bin/git-clock-out b/home/bin/git-clock-out
--- a/home/bin/git-clock-out
+++ b/home/bin/git-clock-out
@@ -20,11 +20,6 @@ usage() {
         cut -c 3-
 }
 
-if [[ "$1" == "help" ]]; then
-    usage
-    exit 2
-fi
-
 duration() {
     ((hours=${1} / 3600))
     ((mins=(${1} % 3600) / 60))
@@ -32,42 +27,51 @@ duration() {
     printf "%02d:%02d:%02d\n" "$hours" "$mins" "$secs"
 }
 
-# Append clock-in and clock-out timestamps (iso and unix)
-CLOCK_IN="$(git show HEAD --no-patch --format=%cD)"
-CLOCK_OUT="$(date +'%a,%e %b %Y %T %z')"
+if [[ "$1" == "help" ]]; then
+    usage
+    exit 2
+fi
 
-# Calculate elapsed since last clock-in
-PREV="$(git show HEAD --no-patch --format=%ct)"
-CURR="$(date +%s)"
-CLOCK_SECS=$((CURR - PREV))
+if git diff --cached --quiet; then
+    echo "Error: Nothing staged."
+    exit 1
+fi
 
-# Calculate total elapsed time
-PREV_DIFFS="$(
+# Collect timestamps
+CLOCK_IN="$(git show HEAD | grep CLOCK-IN: | awk '{ print $2 }')"
+TIME_START="$(git show HEAD | grep START: | sed -E 's/.+START: //')"
+TIME_END="$(date +'%a,%e %b %Y %T %z')"
+
+if [[ -z "${CLOCK_IN}" ]] || [[ -z "${TIME_START}" ]]; then
+    echo "Error: No running clock. Did you forget to clock in?"
+    exit 1
+fi
+
+# Calculate total elapsed time on this branch
+CLOCK_HISTORY_SUM="$(
   git log |
-  grep CLOCK-SECS |
-  sed -E 's/CLOCK-SECS: //' |
+  grep DURATION: |
+  sed -E 's/DURATION: //' |
   paste -sd+ - |
   bc
 )"
 
-TOTAL_SECS=$((PREV_DIFFS + CLOCK_SECS))
-
-CLOCK_ELAPSED="$(duration $CLOCK_SECS)"
-TOTAL_ELAPSED="$(duration $TOTAL_SECS)"
+# Calculate elapsed since last clock-in
+CLOCK_OUT="$(date +%s)"
+CLOCK_SECS=$((CLOCK_OUT - CLOCK_IN))
+TOTAL_SECS=$((CLOCK_HISTORY_SUM + CLOCK_SECS))
 
 # Revise last commit with given commit message and staged work
-SUBJECT=$(git show HEAD --format='%s')
-
+SUBJECT="$(git show HEAD --format='%s')"
 git commit --amend --message="${SUBJECT}
 
-CLOCK-IN: ${CLOCK_IN}
-CLOCK-OUT: ${CLOCK_OUT}
+START: ${TIME_START}
+END: ${TIME_END}
 
-CLOCK-SECS: ${CLOCK_SECS}
-TOTAL-SECS: ${TOTAL_SECS}
+DURATION: ${CLOCK_SECS}
+ELAPSED: $(duration $CLOCK_SECS)
 
-CLOCK-ELAPSED: ${CLOCK_ELAPSED}
-TOTAL-ELAPSED: ${TOTAL_ELAPSED}
+TOTAL: $(duration $TOTAL_SECS)
 " >/dev/null
 
 git commit --amend
