Shell: Tighten up mx script

diff --git a/home/bin/mx b/home/bin/mx
--- a/home/bin/mx
+++ b/home/bin/mx
@@ -8,16 +8,22 @@ function display_help() {
   echo "  Usage: mx [SUBCOMMAND]
 
   Available subcommands:
-    help                    # Displays this menu
-    ls                      # List all running and available sessions
-    select                  # Select a running tmux session to switch to
-    tat                     # Attach to a session named after the pwd, creating if necessary
-    copy [EXISTING] [NEW]   # Copy an existing project to a new project and open.
-    debug [PROJECT]         # Output the shell commands that are generated by tmux.
-    delete [PROJECT]        # Deletes given project
-    doctor                  # Look for problems in your configuration
-    new [PROJECT]           # Create a new project file and open it in your editor
-    start [PROJECT] [SESSION_NAME]  # Start a tmuxinator-managed tmux session."
+    help -- Displays this menu
+    ls   -- List all running and available sessions
+    tat  -- Attach to a PWD-named session if it exists, otherwise create and attach to it
+
+    Fuzzy-Finder commands:
+
+    sat    -- Select and attach to a running tmux session
+    debug  -- Output the shell commands that are generated by tmux.
+    delete -- Deletes given project
+    new    -- Create a new project file and open it in your editor
+
+    To be implemented:
+
+    copy [EXISTING] [NEW] -- Copy an existing project to a new project and open.
+    start [PROJECT] [SESSION_NAME] -- Start a tmuxinator-managed tmux session.
+  "
 }
 
 # issue mx help to see subcommand options
@@ -35,17 +41,17 @@ if [[ "$subcommand" == "ls" ]]; then
   running_sessions="$(tmux ls 2> /dev/null | grep -v 'failed to connect')"
   tmuxinator_templates="$(tmuxinator list | sed -n '1!p')"
 
-  echo "Running Sessions"
+  echo "Running Sessions:"
   echo "$(echo "$running_sessions" | sed 's/^/   /')"
   echo
-  echo "Available Templates:"
+  echo "Available Tmuxinator Templates:"
   echo "$(echo "$tmuxinator_templates" | sed 's/\s\+/\n/g' | sed 's/^/   /')"
 
   exit 0
 fi
 
 
-if [[ "$subcommand" == "select"  ]]; then
+if [[ "$subcommand" == "sat"  ]]; then
   available_sessions="$(tmux ls 2> /dev/null | grep -v 'failed to connect')"
   [[ -z "$available_sessions" ]] && echo "No sessions running." && exit 0
 
@@ -62,10 +68,17 @@ if [[ "$subcommand" == "select"  ]]; then
 fi
 
 # all other subcommands forwarded to tmuxinator
-session="$(tmuxinator list | sed -n '1!p' | sed 's/\s\+/\n/g' | $fzf_command)"
+if [[ "$subcommand" =~ ^start|debug|delete|new$ ]]; then
+  session="$(tmuxinator list | sed -n '1!p' | sed 's/\s\+/\n/g' | $fzf_command)"
 
-# exit quietly if no session selected
-[[ -z "$session" ]] && exit 0
+  # exit quietly if no session selected
+  [[ -z "$session" ]] && exit 0
 
-echo "tmuxinator $subcommand $session"
-tmuxinator $subcommand $session
+  echo "tmuxinator $subcommand $session"
+  tmuxinator $subcommand $session
+fi
+
+
+echo "  Error: Unrecognized subcommand" && echo
+display_help
+exit 1
